export let dashboard = () => import('@/components/homepage/components/main_body/components/dashboard/index.vue') 
export let main_body = () => import('@/components/homepage/components/main_body/index.vue') 
export let sidebar = () => import('@/components/homepage/components/sidebar/index.vue') 
export let topbar = () => import('@/components/homepage/components/topbar/index.vue') 
export let homepage = () => import('@/components/homepage/index.vue') 
export let login_page = () => import('@/components/login_page/login_page.vue') 
export let page_404 = () => import('@/components/page_404/404.vue') 
